# Generated by Django 2.2.2 on 2019-10-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('price', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('rent', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('video_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
