# Generated by Django 2.2.2 on 2019-10-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='occupied',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='cards',
            name='occupier',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
