# Generated by Django 2.2.2 on 2019-10-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_player1_player2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Player1', max_length=200, null=True)),
                ('points', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Player1',
        ),
        migrations.DeleteModel(
            name='Player2',
        ),
    ]
